spring:
  application:
    name=MyMarketplace
  datasource:
    url: jdbc:mysql://localhost:3306/mymarketplace
    username: root
    password: qsxwdc12q
  jpa:
    hibernate:
      ddl-auto: update
  freemarker:
    expose-request-attributes: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB




